print('=-' * 25)
print('SOMA DE DOIS MAIORES VALORES')
print('=-' * 25)
n1 = int(input('DIGITE UM PRIMEIRO NÚMERO: '))
print('=-' * 25)
n2 = int(input('DIGITE O SEGUNDO NÚMERO: '))
print('=-' * 25)
n3 = int(input('DIGITE O TERCEIRO NÚMERO: '))
print('=-' * 25)
lista = [n1, n2, n3] # CRIANDO UMA LISTA COM AS TRÊS VARIÁVEIS
lista.sort(reverse = True) # USANDO O MÉTODO SORT PARA ORGANIZAR DE FORMA CRESCENTE. E EM SEGUIDA FAZENDO UMA INVERSÃO(DECRESCENTE)
print(f'A SOMA DOS SEUS DOIS MAIORES VALORES({lista[0]} E {lista[1]}) VAI DAR {lista[0] + lista[1]}')
print('=-' * 25)
exit()